//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace AindBehaviorServices.MessageProtocol
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class HeartbeatMessage : RegisteredMessages
    {
    
        private MessageType _messageType;
    
        private string _protocolVersion = "0";
    
        private System.DateTimeOffset _timestamp;
    
        private HeartbeatPayload _payload = new HeartbeatPayload();
    
        private string _processId;
    
        private string _hostname;
    
        private string _rigName;
    
        public HeartbeatMessage()
        {
        }
    
        protected HeartbeatMessage(HeartbeatMessage other) : 
                base(other)
        {
            _messageType = other._messageType;
            _protocolVersion = other._protocolVersion;
            _timestamp = other._timestamp;
            _payload = other._payload;
            _processId = other._processId;
            _hostname = other._hostname;
            _rigName = other._rigName;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("message_type", Required=Newtonsoft.Json.Required.Always)]
        public MessageType MessageType
        {
            get
            {
                return _messageType;
            }
            set
            {
                _messageType = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("protocol_version")]
        public string ProtocolVersion
        {
            get
            {
                return _protocolVersion;
            }
            set
            {
                _protocolVersion = value;
            }
        }
    
        /// <summary>
        /// The timestamp of the message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("timestamp", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The timestamp of the message")]
        public System.DateTimeOffset Timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                _timestamp = value;
            }
        }
    
        /// <summary>
        /// The payload for HeartbeatMessage.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("payload", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The payload for HeartbeatMessage.")]
        public HeartbeatPayload Payload
        {
            get
            {
                return _payload;
            }
            set
            {
                _payload = value;
            }
        }
    
        /// <summary>
        /// Process that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("process_id", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Process that created the message")]
        public string ProcessId
        {
            get
            {
                return _processId;
            }
            set
            {
                _processId = value;
            }
        }
    
        /// <summary>
        /// Hostname that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("hostname", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Hostname that created the message")]
        public string Hostname
        {
            get
            {
                return _hostname;
            }
            set
            {
                _hostname = value;
            }
        }
    
        /// <summary>
        /// Rig name that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rig_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Rig name that created the message")]
        public string RigName
        {
            get
            {
                return _rigName;
            }
            set
            {
                _rigName = value;
            }
        }
    
        public System.IObservable<HeartbeatMessage> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HeartbeatMessage(this)));
        }
    
        public System.IObservable<HeartbeatMessage> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HeartbeatMessage(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("message_type = " + _messageType + ", ");
            stringBuilder.Append("protocol_version = " + _protocolVersion + ", ");
            stringBuilder.Append("timestamp = " + _timestamp + ", ");
            stringBuilder.Append("payload = " + _payload + ", ");
            stringBuilder.Append("process_id = " + _processId + ", ");
            stringBuilder.Append("hostname = " + _hostname + ", ");
            stringBuilder.Append("rig_name = " + _rigName);
            return true;
        }
    }


    /// <summary>
    /// A payload for a heartbeat message.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A payload for a heartbeat message.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class HeartbeatPayload
    {
    
        private object _context;
    
        private HeartbeatStatus _status;
    
        public HeartbeatPayload()
        {
        }
    
        protected HeartbeatPayload(HeartbeatPayload other)
        {
            _context = other._context;
            _status = other._status;
        }
    
        /// <summary>
        /// Additional context for the heartbeat message.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("context")]
        [System.ComponentModel.DescriptionAttribute("Additional context for the heartbeat message.")]
        public object Context
        {
            get
            {
                return _context;
            }
            set
            {
                _context = value;
            }
        }
    
        /// <summary>
        /// The status of the heartbeat message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("status", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The status of the heartbeat message")]
        public HeartbeatStatus Status
        {
            get
            {
                return _status;
            }
            set
            {
                _status = value;
            }
        }
    
        public System.IObservable<HeartbeatPayload> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HeartbeatPayload(this)));
        }
    
        public System.IObservable<HeartbeatPayload> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HeartbeatPayload(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("context = " + _context + ", ");
            stringBuilder.Append("status = " + _status);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum HeartbeatStatus
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="0")]
        Ok = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="1")]
        Warning = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="2")]
        Error = 2,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="3")]
        Critical = 3,
    }


    /// <summary>
    /// Log levels for the logging system.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum LogLevel
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="50")]
        Critical = 50,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="40")]
        Error = 40,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="30")]
        Warning = 30,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="20")]
        Info = 20,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="10")]
        Debug = 10,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="0")]
        Notset = 0,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class LogMessage : RegisteredMessages
    {
    
        private MessageType _messageType;
    
        private string _protocolVersion = "0";
    
        private System.DateTimeOffset _timestamp;
    
        private LogPayload _payload = new LogPayload();
    
        private string _processId;
    
        private string _hostname;
    
        private string _rigName;
    
        public LogMessage()
        {
        }
    
        protected LogMessage(LogMessage other) : 
                base(other)
        {
            _messageType = other._messageType;
            _protocolVersion = other._protocolVersion;
            _timestamp = other._timestamp;
            _payload = other._payload;
            _processId = other._processId;
            _hostname = other._hostname;
            _rigName = other._rigName;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("message_type", Required=Newtonsoft.Json.Required.Always)]
        public MessageType MessageType
        {
            get
            {
                return _messageType;
            }
            set
            {
                _messageType = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("protocol_version")]
        public string ProtocolVersion
        {
            get
            {
                return _protocolVersion;
            }
            set
            {
                _protocolVersion = value;
            }
        }
    
        /// <summary>
        /// The timestamp of the message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("timestamp", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The timestamp of the message")]
        public System.DateTimeOffset Timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                _timestamp = value;
            }
        }
    
        /// <summary>
        /// The payload for LogMessage.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("payload", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The payload for LogMessage.")]
        public LogPayload Payload
        {
            get
            {
                return _payload;
            }
            set
            {
                _payload = value;
            }
        }
    
        /// <summary>
        /// Process that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("process_id", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Process that created the message")]
        public string ProcessId
        {
            get
            {
                return _processId;
            }
            set
            {
                _processId = value;
            }
        }
    
        /// <summary>
        /// Hostname that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("hostname", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Hostname that created the message")]
        public string Hostname
        {
            get
            {
                return _hostname;
            }
            set
            {
                _hostname = value;
            }
        }
    
        /// <summary>
        /// Rig name that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rig_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Rig name that created the message")]
        public string RigName
        {
            get
            {
                return _rigName;
            }
            set
            {
                _rigName = value;
            }
        }
    
        public System.IObservable<LogMessage> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LogMessage(this)));
        }
    
        public System.IObservable<LogMessage> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LogMessage(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("message_type = " + _messageType + ", ");
            stringBuilder.Append("protocol_version = " + _protocolVersion + ", ");
            stringBuilder.Append("timestamp = " + _timestamp + ", ");
            stringBuilder.Append("payload = " + _payload + ", ");
            stringBuilder.Append("process_id = " + _processId + ", ");
            stringBuilder.Append("hostname = " + _hostname + ", ");
            stringBuilder.Append("rig_name = " + _rigName);
            return true;
        }
    }


    /// <summary>
    /// A payload for a log message.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A payload for a log message.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class LogPayload
    {
    
        private string _message;
    
        private LogLevel _level = AindBehaviorServices.MessageProtocol.LogLevel.Debug;
    
        private object _context;
    
        private string _applicationVersion;
    
        public LogPayload()
        {
        }
    
        protected LogPayload(LogPayload other)
        {
            _message = other._message;
            _level = other._level;
            _context = other._context;
            _applicationVersion = other._applicationVersion;
        }
    
        /// <summary>
        /// The message of the log
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("message", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The message of the log")]
        public string Message
        {
            get
            {
                return _message;
            }
            set
            {
                _message = value;
            }
        }
    
        /// <summary>
        /// The level of the log message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("level")]
        [System.ComponentModel.DescriptionAttribute("The level of the log message")]
        public LogLevel Level
        {
            get
            {
                return _level;
            }
            set
            {
                _level = value;
            }
        }
    
        /// <summary>
        /// Additional context for the log message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("context")]
        [System.ComponentModel.DescriptionAttribute("Additional context for the log message")]
        public object Context
        {
            get
            {
                return _context;
            }
            set
            {
                _context = value;
            }
        }
    
        /// <summary>
        /// The version of the application
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("application_version")]
        [System.ComponentModel.DescriptionAttribute("The version of the application")]
        public string ApplicationVersion
        {
            get
            {
                return _applicationVersion;
            }
            set
            {
                _applicationVersion = value;
            }
        }
    
        public System.IObservable<LogPayload> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LogPayload(this)));
        }
    
        public System.IObservable<LogPayload> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LogPayload(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("message = " + _message + ", ");
            stringBuilder.Append("level = " + _level + ", ");
            stringBuilder.Append("context = " + _context + ", ");
            stringBuilder.Append("application_version = " + _applicationVersion);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// A message is a generic message that can be used to track any message that occurs in the software.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A message is a generic message that can be used to track any message that occurs " +
        "in the software.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Message
    {
    
        private string _clsType = "";
    
        private MessageType _messageType;
    
        private string _protocolVersion = "0";
    
        private System.DateTimeOffset _timestamp;
    
        private object _payload;
    
        private string _processId;
    
        private string _hostname;
    
        private string _rigName;
    
        public Message()
        {
        }
    
        protected Message(Message other)
        {
            _clsType = other._clsType;
            _messageType = other._messageType;
            _protocolVersion = other._protocolVersion;
            _timestamp = other._timestamp;
            _payload = other._payload;
            _processId = other._processId;
            _hostname = other._hostname;
            _rigName = other._rigName;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("cls_type")]
        public string ClsType
        {
            get
            {
                return _clsType;
            }
            set
            {
                _clsType = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("message_type", Required=Newtonsoft.Json.Required.Always)]
        public MessageType MessageType
        {
            get
            {
                return _messageType;
            }
            set
            {
                _messageType = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("protocol_version")]
        public string ProtocolVersion
        {
            get
            {
                return _protocolVersion;
            }
            set
            {
                _protocolVersion = value;
            }
        }
    
        /// <summary>
        /// The timestamp of the message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("timestamp", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The timestamp of the message")]
        public System.DateTimeOffset Timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                _timestamp = value;
            }
        }
    
        /// <summary>
        /// The payload of the message
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("payload", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The payload of the message")]
        public object Payload
        {
            get
            {
                return _payload;
            }
            set
            {
                _payload = value;
            }
        }
    
        /// <summary>
        /// Process that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("process_id", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Process that created the message")]
        public string ProcessId
        {
            get
            {
                return _processId;
            }
            set
            {
                _processId = value;
            }
        }
    
        /// <summary>
        /// Hostname that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("hostname", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Hostname that created the message")]
        public string Hostname
        {
            get
            {
                return _hostname;
            }
            set
            {
                _hostname = value;
            }
        }
    
        /// <summary>
        /// Rig name that created the message
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rig_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Rig name that created the message")]
        public string RigName
        {
            get
            {
                return _rigName;
            }
            set
            {
                _rigName = value;
            }
        }
    
        public System.IObservable<Message> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Message(this)));
        }
    
        public System.IObservable<Message> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Message(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("cls_type = " + _clsType + ", ");
            stringBuilder.Append("message_type = " + _messageType + ", ");
            stringBuilder.Append("protocol_version = " + _protocolVersion + ", ");
            stringBuilder.Append("timestamp = " + _timestamp + ", ");
            stringBuilder.Append("payload = " + _payload + ", ");
            stringBuilder.Append("process_id = " + _processId + ", ");
            stringBuilder.Append("hostname = " + _hostname + ", ");
            stringBuilder.Append("rig_name = " + _rigName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum MessageType
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="request")]
        Request = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="reply")]
        Reply = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="event")]
        Event = 2,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "cls_type")]
    [JsonInheritanceAttribute("LogMessage", typeof(LogMessage))]
    [JsonInheritanceAttribute("HeartbeatMessage", typeof(HeartbeatMessage))]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RegisteredMessages
    {
    
        public RegisteredMessages()
        {
        }
    
        protected RegisteredMessages(RegisteredMessages other)
        {
        }
    
        public System.IObservable<RegisteredMessages> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RegisteredMessages(this)));
        }
    
        public System.IObservable<RegisteredMessages> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RegisteredMessages(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class MessageProtocol
    {
    
        private RegisteredMessages _registeredMessage;
    
        private Message _message = new Message();
    
        protected MessageProtocol()
        {
        }
    
        protected MessageProtocol(MessageProtocol other)
        {
            _registeredMessage = other._registeredMessage;
            _message = other._message;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("registered_message", Required=Newtonsoft.Json.Required.Always)]
        public RegisteredMessages RegisteredMessage
        {
            get
            {
                return _registeredMessage;
            }
            set
            {
                _registeredMessage = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("message", Required=Newtonsoft.Json.Required.Always)]
        public Message Message
        {
            get
            {
                return _message;
            }
            set
            {
                _message = value;
            }
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("registered_message = " + _registeredMessage + ", ");
            stringBuilder.Append("message = " + _message);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; private set; }

        public System.Type Type { get; private set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Combinator)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LogMessage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HeartbeatMessage>))]
    public partial class MatchRegisteredMessages : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = Type;
            var returnType = typeMapping != null ? typeMapping.GetType().GetGenericArguments()[0] : typeof(RegisteredMessages);
            return System.Linq.Expressions.Expression.Call(
                typeof(MatchRegisteredMessages),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

    
        private static System.IObservable<TResult> Process<TResult>(System.IObservable<RegisteredMessages> source)
            where TResult : RegisteredMessages
        {
            return System.Reactive.Linq.Observable.Create<TResult>(observer =>
            {
                var sourceObserver = System.Reactive.Observer.Create<RegisteredMessages>(
                    value =>
                    {
                        var match = value as TResult;
                        if (match != null) observer.OnNext(match);
                    },
                    observer.OnError,
                    observer.OnCompleted);
                return System.ObservableExtensions.SubscribeSafe(source, sourceObserver);
            });
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    public partial class SerializeToJson
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value));
        }

        public System.IObservable<string> Process(System.IObservable<HeartbeatMessage> source)
        {
            return Process<HeartbeatMessage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HeartbeatPayload> source)
        {
            return Process<HeartbeatPayload>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LogMessage> source)
        {
            return Process<LogMessage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LogPayload> source)
        {
            return Process<LogPayload>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Message> source)
        {
            return Process<Message>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RegisteredMessages> source)
        {
            return Process<RegisteredMessages>(source);
        }

        public System.IObservable<string> Process(System.IObservable<MessageProtocol> source)
        {
            return Process<MessageProtocol>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HeartbeatMessage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HeartbeatPayload>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LogMessage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LogPayload>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Message>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RegisteredMessages>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MessageProtocol>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<MessageProtocol>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}